---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'Creates an RDS instance in the private subnet'

Parameters:
  DBStorageSize:
    Type: String
    Default: 20
  DatabaseSecurityGroup:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
  DBInstanceType:
    Type: String
    Default: db.t3.micro
    AllowedValues:
    - db.t3.micro
    - db.t3.small
    - db.t3.medium
  DBInstanceName:
    Type: String
    Default: 'my-prod-db'
  DBParameterGroup:
    Type: String
    Default: 'my-prod-rds-pg'
  DBEngine:
    Type: String
    Default: MySQL
  DBUser:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
    Default: 'admin123'  ## Just for understanding. Ideally secrets manager must be used.
  PrivateSubnet:
    Type: AWS::EC2::Subnet::Id 
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id 

Resources:
  SubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group associated for the DB instance 
      SubnetIds:
      - Ref: PrivateSubnet
      - Ref: PrivateSubnet2

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties: 
      AllocatedStorage:   
        Ref: DBStorageSize
      MaxAllocatedStorage: '50'
      BackupRetentionPeriod: '3'
      CopyTagsToSnapshot: true
      CACertificateIdentifier: 'rds-ca-2019'
      DBName: 'myproddb'
      DBInstanceClass: 
        Ref: DBInstanceType
      DBInstanceIdentifier:
        Ref: DBInstanceName
      DBSubnetGroupName:
        Ref: SubnetGroup
      DBParameterGroupName: 
        Ref: DBParameterGroup
      EnableCloudwatchLogsExports: ['slowquery','general','audit','error']
      Engine:
        Ref: DBEngine
      EngineVersion: '5.6.48'
      MasterUsername:
        Ref: DBUser
      MasterUserPassword:
        Ref: DBPassword
      Port: 3306
      PubliclyAccessible: false
      StorageType: 'gp2'
      DeletionProtection: false
      VPCSecurityGroups:
        Ref: DatabaseSecurityGroup