---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'Creates an RDS instance in the private subnet'

Parameters:
  DBStorageSize:
    Type: String
    Default: 20
  DatabseSecurityGroup:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
  DBInstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
    - t3.micro
    - t3.small
    - t3.medium
  DBInstanceName:
    Type: String
    Default: 'my-prod-db'
  DBSubnetGroup:
    Type: String
  DBParameterGroup:
    Type: String
  DBEngine:
    Type: String
    Default: MySQL
  DBEngineVersion:
    Type: String
    Default: '5.6.40'
  DBUser:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
    Default: 'admin123'  ## Just for understanding. Ideally secrets manager must be used.
  DBPort:
    Type: String
    Default: '3306' 

Resources:
  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties: 
      AllocatedStorage:   
        Ref: DBStorageSize
      MaxAllocatedStorage: '50'
      BackupRetentionPeriod: '3'
      CopyTagsToSnapshot: true
      CACertificateIdentifier: 'rds-ca-2019'
      DBName: 'my-prod-rds'
      DBInstanceClass: 
        Ref: DBInstanceType
      DBInstanceIdentifier:
        Ref: DBInstanceName
      DBSubnetGroupName: DBSubnetGroup
      DBParameterGroupName: DBParameterGroup
      EnableCloudwatchLogsExports: ['slowquery','general','audit','error']
      Engine:
        Ref: DBEngine
      EngineVersion: DBEngineVersion
      MasterUsername:
        Ref: DBUser
      MasterUserPassword:
        Ref: DBPassword
      Port: DBPort
      PubliclyAccessible: false
      StorageType: 'gp2'
      DeletionProtection: false
      VPCSecurityGroups:
      - Ref: DatabseSecurityGroup