---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'This template creates bastion host in the public subnet'

Parameters:
  RoleName:
    Type: String
    Default: 'rcloud-ec2-role'
  Instance:
    Type: String
    Default: 't3.nano'
    AllowedValues:
    - 't3.nano'
    - 't3.micro'
    - 't3.small'
  WebserverAMI:
    Type: String
    Default: 'ami-02b5fbc2cb28b77b8'
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  SubnetID:
    Type: AWS::EC2::Subnet::Id
  WebserverSecurityGroup:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'

Resources:
  WebserverHost:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: Instance
      KeyName: 
        Ref: KeyName
      ImageId:
        Ref: WebserverAMI
      IamInstanceProfile:
        Ref: RoleName
      NetworkInterfaces:  
      - AssociatePublicIpAddress: 'false'
        DeleteOnTermination: 'true'
        DeviceIndex: 0
        GroupSet:
          Ref: WebserverSecurityGroup
        SubnetId:
          Ref: SubnetID

Outputs:
  WebserverInstance:
    Description: 'Output the instance ID for the target group'
    Value:
      Ref: WebserverHost