---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'Creates the ELB in the public subnet'

Parameters:
  ELBSecurityGroup:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
  # subnets in which ELB to launch
  PublicSubnet:
    Type: AWS::EC2::Subnet::Id
  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id

Resources:
  ApplicationELB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      SecurityGroups:
        Ref: ELBSecurityGroup
      Scheme: 'internet-facing'
      Subnets:
      - Ref: PublicSubnet
      - Ref: PublicSubnet2
      Name: 'my-prod-application-elb'

Outputs:
  ELBArn:
    Description: 'Output the ELB Arn'
    Value:
      Ref: ApplicationELB